# SPDX-FileCopyrightText: 2021 Future PLC
#
# SPDX-License-Identifier: CC0-1.0

name: "Notify slack"
description: "Sends a notification to slack"

branding:
  icon: paperclip
  color: gray-dark

inputs:
  slackToken:
    description: "SlackMessage token to use"
    required: true
  githubToken:
    description: "SlackMessage token to use"
    required: true
  jiraToken:
    description: "The thing that is getting deployed"
    required: true
  action:
    description: "Which notification type to send"
    required: true
  name:
    description: "The thing that is getting deployed"
    required: false
    default: 'FEv2'

runs:
  using: "node16"
  main: "src/action.js"

# vim: nospell ts=2 expandtab
