# SPDX-FileCopyrightText: 2021 Future PLC
#
# SPDX-License-Identifier: BSD-2-Clause

name: JS Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  es-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ESLint
        run: npm install eslint@8.39.0
      - name: Run ESLint
        run: npx eslint . --ext .js --ignore-pattern ./node_modules
